
/**
 * @file attribs.h
 *
 * Defines the AttribUnion and attrib structures.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: attribs.h.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#ifndef _SAC_ATTRIBS_H_
#define _SAC_ATTRIBS_H_

#include "types.h"


/******************************************************************************
 * For each node a structure of its attributes is defined, named 
 * ATTRIBS_<nodename>
 *****************************************************************************/
struct ATTRIBS_N_ASSIGN
{
};
struct ATTRIBS_N_BINOP
{
  binop Op;
};
struct ATTRIBS_N_BOOL
{
  bool Value;
};
struct ATTRIBS_N_COMMA
{
};
struct ATTRIBS_N_DECLARATIONS
{
};
struct ATTRIBS_N_ERROR
{
  char *message;
  compiler_phase_t anyphase;
};
struct ATTRIBS_N_EXTERN
{
};
struct ATTRIBS_N_FLOAT
{
  float Value;
};
struct ATTRIBS_N_FUNBODYBLOCK
{
};
struct ATTRIBS_N_FUNDEC
{
};
struct ATTRIBS_N_FUNDEF
{
};
struct ATTRIBS_N_FUNHEADER
{
};
struct ATTRIBS_N_GLOBALDEC
{
};
struct ATTRIBS_N_GLOBALDEF
{
};
struct ATTRIBS_N_ID
{
  char *Id;
};
struct ATTRIBS_N_L_BRACKET
{
};
struct ATTRIBS_N_L_CURLY_BRACKET
{
};
struct ATTRIBS_N_MODULE
{
  int Count_all;
  int Count_add;
  int Count_sub;
  int Count_mul;
  int Count_div;
  int Count_mod;
};
struct ATTRIBS_N_MONOP
{
  monop Op;
};
struct ATTRIBS_N_NUM
{
  int Value;
};
struct ATTRIBS_N_PARAM
{
};
struct ATTRIBS_N_PARAMS
{
};
struct ATTRIBS_N_PROGRAM
{
};
struct ATTRIBS_N_R_BRACKET
{
};
struct ATTRIBS_N_R_CURLY_BRACKET
{
};
struct ATTRIBS_N_SEMICOLON
{
};
struct ATTRIBS_N_STMTS
{
};
struct ATTRIBS_N_SYMBOLTABLEENTRY
{
};
struct ATTRIBS_N_VAR
{
  char *Name;
  node *Decl;
};
struct ATTRIBS_N_VARLET
{
  char *Name;
  node *Decl;
};
/*****************************************************************************
 * This union handles all different types of attributes. Its members are
 * called N_nodename.
 ****************************************************************************/
struct ATTRIBUNION
{
  struct ATTRIBS_N_ASSIGN *N_assign;
  struct ATTRIBS_N_BINOP *N_binop;
  struct ATTRIBS_N_BOOL *N_bool;
  struct ATTRIBS_N_COMMA *N_comma;
  struct ATTRIBS_N_DECLARATIONS *N_declarations;
  struct ATTRIBS_N_ERROR *N_error;
  struct ATTRIBS_N_EXTERN *N_extern;
  struct ATTRIBS_N_FLOAT *N_float;
  struct ATTRIBS_N_FUNBODYBLOCK *N_funbodyblock;
  struct ATTRIBS_N_FUNDEC *N_fundec;
  struct ATTRIBS_N_FUNDEF *N_fundef;
  struct ATTRIBS_N_FUNHEADER *N_funheader;
  struct ATTRIBS_N_GLOBALDEC *N_globaldec;
  struct ATTRIBS_N_GLOBALDEF *N_globaldef;
  struct ATTRIBS_N_ID *N_id;
  struct ATTRIBS_N_L_BRACKET *N_l_bracket;
  struct ATTRIBS_N_L_CURLY_BRACKET *N_l_curly_bracket;
  struct ATTRIBS_N_MODULE *N_module;
  struct ATTRIBS_N_MONOP *N_monop;
  struct ATTRIBS_N_NUM *N_num;
  struct ATTRIBS_N_PARAM *N_param;
  struct ATTRIBS_N_PARAMS *N_params;
  struct ATTRIBS_N_PROGRAM *N_program;
  struct ATTRIBS_N_R_BRACKET *N_r_bracket;
  struct ATTRIBS_N_R_CURLY_BRACKET *N_r_curly_bracket;
  struct ATTRIBS_N_SEMICOLON *N_semicolon;
  struct ATTRIBS_N_STMTS *N_stmts;
  struct ATTRIBS_N_SYMBOLTABLEENTRY *N_symboltableentry;
  struct ATTRIBS_N_VAR *N_var;
  struct ATTRIBS_N_VARLET *N_varlet;
};
#endif /* _SAC_ATTRIBS_H_ */
