
/**
 * @file copy_node.c
 *
 * Functions needed by copy traversal.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * copy_node.c.xsl.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

/**
 * @defgroup copy Copy Tree Functions.
 *
 * Functions needed by copy traversal.
 *
 * @{
 */


#include "copy_node.h"
#include "copy_info.h"
#include "traverse.h"
#include "dbug.h"
#include "tree_basic.h"
#include "str.h"
#include "lookup_table.h"


#define COPYTRAV( node, info) (node != NULL) ? TRAVdo( node, info) : node


/** <!--******************************************************************-->
 *
 * @fn COPYassign
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Assign node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYassign (node * arg_node, info * arg_info)
{
  node *result = TBmakeAssign (NULL, NULL);
  DBUG_ENTER ("COPYassign");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  ASSIGN_LET (result) = COPYTRAV (ASSIGN_LET (arg_node), arg_info);
  ASSIGN_EXPR (result) = COPYTRAV (ASSIGN_EXPR (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYbinop
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node BinOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYbinop (node * arg_node, info * arg_info)
{
  node *result = TBmakeBinop (BO_unknown, NULL, NULL);
  DBUG_ENTER ("COPYbinop");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  BINOP_OP (result) = BINOP_OP (arg_node);
  /* Copy sons */
  BINOP_LEFT (result) = COPYTRAV (BINOP_LEFT (arg_node), arg_info);
  BINOP_RIGHT (result) = COPYTRAV (BINOP_RIGHT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYbool
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Bool node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYbool (node * arg_node, info * arg_info)
{
  node *result = TBmakeBool (FALSE);
  DBUG_ENTER ("COPYbool");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  BOOL_VALUE (result) = BOOL_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYcomma
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Comma node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYcomma (node * arg_node, info * arg_info)
{
  node *result = TBmakeComma ();
  DBUG_ENTER ("COPYcomma");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYdeclarations
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Declarations node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYdeclarations (node * arg_node, info * arg_info)
{
  node *result = TBmakeDeclarations (NULL, NULL);
  DBUG_ENTER ("COPYdeclarations");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  DECLARATIONS_DECLARATION (result) =
    COPYTRAV (DECLARATIONS_DECLARATION (arg_node), arg_info);
  DECLARATIONS_DECLARATIONS (result) =
    COPYTRAV (DECLARATIONS_DECLARATIONS (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYerror
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Error node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYerror (node * arg_node, info * arg_info)
{
  node *result = TBmakeError (NULL, PH_initial, NULL);
  DBUG_ENTER ("COPYerror");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  ERROR_MESSAGE (result) = STRcpy (ERROR_MESSAGE (arg_node));
  ERROR_ANYPHASE (result) = ERROR_ANYPHASE (arg_node);
  /* Copy sons */
  ERROR_NEXT (result) = COPYTRAV (ERROR_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYextern
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Extern node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYextern (node * arg_node, info * arg_info)
{
  node *result = TBmakeExtern ();
  DBUG_ENTER ("COPYextern");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfloat
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Float node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfloat (node * arg_node, info * arg_info)
{
  node *result = TBmakeFloat (0.0);
  DBUG_ENTER ("COPYfloat");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  FLOAT_VALUE (result) = FLOAT_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfunbodyblock
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunBodyBlock node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfunbodyblock (node * arg_node, info * arg_info)
{
  node *result = TBmakeFunbodyblock (NULL, NULL, NULL);
  DBUG_ENTER ("COPYfunbodyblock");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  FUNBODYBLOCK_L_CURLY_BRACKET (result) =
    COPYTRAV (FUNBODYBLOCK_L_CURLY_BRACKET (arg_node), arg_info);
  FUNBODYBLOCK_FUNBODY (result) =
    COPYTRAV (FUNBODYBLOCK_FUNBODY (arg_node), arg_info);
  FUNBODYBLOCK_R_CURLY_BRACKET (result) =
    COPYTRAV (FUNBODYBLOCK_R_CURLY_BRACKET (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfundec
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfundec (node * arg_node, info * arg_info)
{
  node *result = TBmakeFundec (NULL, NULL, NULL);
  DBUG_ENTER ("COPYfundec");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  FUNDEC_KEYWORD (result) = COPYTRAV (FUNDEC_KEYWORD (arg_node), arg_info);
  FUNDEC_FUNHEADER (result) =
    COPYTRAV (FUNDEC_FUNHEADER (arg_node), arg_info);
  FUNDEC_SEMICOLON (result) =
    COPYTRAV (FUNDEC_SEMICOLON (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfundef
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunDef node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfundef (node * arg_node, info * arg_info)
{
  node *result = TBmakeFundef (NULL, NULL, NULL);
  DBUG_ENTER ("COPYfundef");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  FUNDEF_KEYWORD (result) = COPYTRAV (FUNDEF_KEYWORD (arg_node), arg_info);
  FUNDEF_FUNHEADER (result) =
    COPYTRAV (FUNDEF_FUNHEADER (arg_node), arg_info);
  FUNDEF_FUNBODYBLOCK (result) =
    COPYTRAV (FUNDEF_FUNBODYBLOCK (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfunheader
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunHeader node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfunheader (node * arg_node, info * arg_info)
{
  node *result = TBmakeFunheader (NULL, NULL, NULL, NULL, NULL);
  DBUG_ENTER ("COPYfunheader");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  FUNHEADER_RETTYPE (result) =
    COPYTRAV (FUNHEADER_RETTYPE (arg_node), arg_info);
  FUNHEADER_ID (result) = COPYTRAV (FUNHEADER_ID (arg_node), arg_info);
  FUNHEADER_L_BRACKET (result) =
    COPYTRAV (FUNHEADER_L_BRACKET (arg_node), arg_info);
  FUNHEADER_PARAMS (result) =
    COPYTRAV (FUNHEADER_PARAMS (arg_node), arg_info);
  FUNHEADER_R_BRACKET (result) =
    COPYTRAV (FUNHEADER_R_BRACKET (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYglobaldec
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node GlobalDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYglobaldec (node * arg_node, info * arg_info)
{
  node *result = TBmakeGlobaldec (NULL, NULL, NULL, NULL);
  DBUG_ENTER ("COPYglobaldec");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  GLOBALDEC_EXTERN (result) =
    COPYTRAV (GLOBALDEC_EXTERN (arg_node), arg_info);
  GLOBALDEC_TYPE (result) = COPYTRAV (GLOBALDEC_TYPE (arg_node), arg_info);
  GLOBALDEC_ID (result) = COPYTRAV (GLOBALDEC_ID (arg_node), arg_info);
  GLOBALDEC_SEMICOLON (result) =
    COPYTRAV (GLOBALDEC_SEMICOLON (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYglobaldef
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node GlobalDef node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYglobaldef (node * arg_node, info * arg_info)
{
  node *result = TBmakeGlobaldef (NULL, NULL, NULL, NULL, NULL);
  DBUG_ENTER ("COPYglobaldef");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  GLOBALDEF_EXPORT (result) =
    COPYTRAV (GLOBALDEF_EXPORT (arg_node), arg_info);
  GLOBALDEF_TYPE (result) = COPYTRAV (GLOBALDEF_TYPE (arg_node), arg_info);
  GLOBALDEF_ID (result) = COPYTRAV (GLOBALDEF_ID (arg_node), arg_info);
  GLOBALDEF_EXPR (result) = COPYTRAV (GLOBALDEF_EXPR (arg_node), arg_info);
  GLOBALDEF_SEMICOLON (result) =
    COPYTRAV (GLOBALDEF_SEMICOLON (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYid
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Id node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYid (node * arg_node, info * arg_info)
{
  node *result = TBmakeId (NULL);
  DBUG_ENTER ("COPYid");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  ID_ID (result) = STRcpy (ID_ID (arg_node));
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYl_bracket
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node L_bracket node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYl_bracket (node * arg_node, info * arg_info)
{
  node *result = TBmakeL_bracket ();
  DBUG_ENTER ("COPYl_bracket");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYl_curly_bracket
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node L_curly_bracket node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYl_curly_bracket (node * arg_node, info * arg_info)
{
  node *result = TBmakeL_curly_bracket ();
  DBUG_ENTER ("COPYl_curly_bracket");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYmodule
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Module node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYmodule (node * arg_node, info * arg_info)
{
  node *result = TBmakeModule (0, 0, 0, 0, 0, 0, NULL);
  DBUG_ENTER ("COPYmodule");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  MODULE_COUNT_ALL (result) = MODULE_COUNT_ALL (arg_node);
  MODULE_COUNT_ADD (result) = MODULE_COUNT_ADD (arg_node);
  MODULE_COUNT_SUB (result) = MODULE_COUNT_SUB (arg_node);
  MODULE_COUNT_MUL (result) = MODULE_COUNT_MUL (arg_node);
  MODULE_COUNT_DIV (result) = MODULE_COUNT_DIV (arg_node);
  MODULE_COUNT_MOD (result) = MODULE_COUNT_MOD (arg_node);
  /* Copy sons */
  MODULE_STMTS (result) = COPYTRAV (MODULE_STMTS (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYmonop
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node MonOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYmonop (node * arg_node, info * arg_info)
{
  node *result = TBmakeMonop (MO_unknown, NULL);
  DBUG_ENTER ("COPYmonop");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  MONOP_OP (result) = MONOP_OP (arg_node);
  /* Copy sons */
  MONOP_RIGHT (result) = COPYTRAV (MONOP_RIGHT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYnum
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Num node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYnum (node * arg_node, info * arg_info)
{
  node *result = TBmakeNum (0);
  DBUG_ENTER ("COPYnum");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  NUM_VALUE (result) = NUM_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYparam
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Param node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYparam (node * arg_node, info * arg_info)
{
  node *result = TBmakeParam (NULL, NULL);
  DBUG_ENTER ("COPYparam");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  PARAM_RETTYPE (result) = COPYTRAV (PARAM_RETTYPE (arg_node), arg_info);
  PARAM_ID (result) = COPYTRAV (PARAM_ID (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYparams
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Params node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYparams (node * arg_node, info * arg_info)
{
  node *result = TBmakeParams (NULL, NULL, NULL);
  DBUG_ENTER ("COPYparams");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  PARAMS_PARAM (result) = COPYTRAV (PARAMS_PARAM (arg_node), arg_info);
  PARAMS_COMMA (result) = COPYTRAV (PARAMS_COMMA (arg_node), arg_info);
  PARAMS_PARAMS (result) = COPYTRAV (PARAMS_PARAMS (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYprogram
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Program node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYprogram (node * arg_node, info * arg_info)
{
  node *result = TBmakeProgram (NULL);
  DBUG_ENTER ("COPYprogram");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  PROGRAM_DECLARATIONS (result) =
    COPYTRAV (PROGRAM_DECLARATIONS (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYr_bracket
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node R_bracket node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYr_bracket (node * arg_node, info * arg_info)
{
  node *result = TBmakeR_bracket ();
  DBUG_ENTER ("COPYr_bracket");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYr_curly_bracket
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node R_curly_bracket node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYr_curly_bracket (node * arg_node, info * arg_info)
{
  node *result = TBmakeR_curly_bracket ();
  DBUG_ENTER ("COPYr_curly_bracket");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYsemicolon
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Semicolon node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYsemicolon (node * arg_node, info * arg_info)
{
  node *result = TBmakeSemicolon ();
  DBUG_ENTER ("COPYsemicolon");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYstmts
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Stmts node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYstmts (node * arg_node, info * arg_info)
{
  node *result = TBmakeStmts (NULL, NULL);
  DBUG_ENTER ("COPYstmts");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  STMTS_STMT (result) = COPYTRAV (STMTS_STMT (arg_node), arg_info);
  STMTS_NEXT (result) = COPYTRAV (STMTS_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYsymboltableentry
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node SymbolTableEntry node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYsymboltableentry (node * arg_node, info * arg_info)
{
  node *result = TBmakeSymboltableentry ();
  DBUG_ENTER ("COPYsymboltableentry");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYvar
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Var node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYvar (node * arg_node, info * arg_info)
{
  node *result = TBmakeVar (NULL);
  DBUG_ENTER ("COPYvar");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  VAR_NAME (result) = STRcpy (VAR_NAME (arg_node));
  VAR_DECL (result) =
    LUTsearchInLutPp (INFO_LUT (arg_info), VAR_DECL (arg_node));
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYvarlet
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node VarLet node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYvarlet (node * arg_node, info * arg_info)
{
  node *result = TBmakeVarlet (NULL);
  DBUG_ENTER ("COPYvarlet");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  VARLET_NAME (result) = STRcpy (VARLET_NAME (arg_node));
  VARLET_DECL (result) =
    LUTsearchInLutPp (INFO_LUT (arg_info), VARLET_DECL (arg_node));
  /* Return value */
  DBUG_RETURN (result);
}

/**
 * @}
 */
