
/**
 * @file sons.h
 *
 * Defines the NodesUnion and node structures.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: sons.h.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#ifndef _SAC_SONS_H_
#define _SAC_SONS_H_

#include "types.h"


/******************************************************************************
 * For each node a structure of its sons is defined, named 
 * SONS_<nodename>
 *****************************************************************************/
struct SONS_N_ASSIGN
{
  node *Let;
  node *Expr;
};
struct SONS_N_BINOP
{
  node *Left;
  node *Right;
};
struct SONS_N_BOOL
{
};
struct SONS_N_COMMA
{
};
struct SONS_N_DECLARATIONS
{
  node *Declaration;
  node *Declarations;
};
struct SONS_N_ERROR
{
  node *Next;
};
struct SONS_N_EXTERN
{
};
struct SONS_N_FLOAT
{
};
struct SONS_N_FUNBODYBLOCK
{
  node *L_curly_bracket;
  node *FunBody;
  node *R_curly_bracket;
};
struct SONS_N_FUNDEC
{
  node *Keyword;
  node *FunHeader;
  node *Semicolon;
};
struct SONS_N_FUNDEF
{
  node *Keyword;
  node *FunHeader;
  node *FunBodyBlock;
};
struct SONS_N_FUNHEADER
{
  node *RetType;
  node *Id;
  node *L_bracket;
  node *Params;
  node *R_bracket;
};
struct SONS_N_GLOBALDEC
{
  node *Extern;
  node *Type;
  node *Id;
  node *Semicolon;
};
struct SONS_N_GLOBALDEF
{
  node *Export;
  node *Type;
  node *Id;
  node *Expr;
  node *Semicolon;
};
struct SONS_N_ID
{
};
struct SONS_N_L_BRACKET
{
};
struct SONS_N_L_CURLY_BRACKET
{
};
struct SONS_N_MODULE
{
  node *Stmts;
};
struct SONS_N_MONOP
{
  node *Right;
};
struct SONS_N_NUM
{
};
struct SONS_N_PARAM
{
  node *RetType;
  node *Id;
};
struct SONS_N_PARAMS
{
  node *Param;
  node *Comma;
  node *Params;
};
struct SONS_N_PROGRAM
{
  node *Declarations;
};
struct SONS_N_R_BRACKET
{
};
struct SONS_N_R_CURLY_BRACKET
{
};
struct SONS_N_SEMICOLON
{
};
struct SONS_N_STMTS
{
  node *Stmt;
  node *Next;
};
struct SONS_N_SYMBOLTABLEENTRY
{
};
struct SONS_N_VAR
{
};
struct SONS_N_VARLET
{
};
/*****************************************************************************
 * This union handles all different types of sons. Its members are
 * called N_nodename.
 ****************************************************************************/
struct SONUNION
{
  struct SONS_N_ASSIGN *N_assign;
  struct SONS_N_BINOP *N_binop;
  struct SONS_N_BOOL *N_bool;
  struct SONS_N_COMMA *N_comma;
  struct SONS_N_DECLARATIONS *N_declarations;
  struct SONS_N_ERROR *N_error;
  struct SONS_N_EXTERN *N_extern;
  struct SONS_N_FLOAT *N_float;
  struct SONS_N_FUNBODYBLOCK *N_funbodyblock;
  struct SONS_N_FUNDEC *N_fundec;
  struct SONS_N_FUNDEF *N_fundef;
  struct SONS_N_FUNHEADER *N_funheader;
  struct SONS_N_GLOBALDEC *N_globaldec;
  struct SONS_N_GLOBALDEF *N_globaldef;
  struct SONS_N_ID *N_id;
  struct SONS_N_L_BRACKET *N_l_bracket;
  struct SONS_N_L_CURLY_BRACKET *N_l_curly_bracket;
  struct SONS_N_MODULE *N_module;
  struct SONS_N_MONOP *N_monop;
  struct SONS_N_NUM *N_num;
  struct SONS_N_PARAM *N_param;
  struct SONS_N_PARAMS *N_params;
  struct SONS_N_PROGRAM *N_program;
  struct SONS_N_R_BRACKET *N_r_bracket;
  struct SONS_N_R_CURLY_BRACKET *N_r_curly_bracket;
  struct SONS_N_SEMICOLON *N_semicolon;
  struct SONS_N_STMTS *N_stmts;
  struct SONS_N_SYMBOLTABLEENTRY *N_symboltableentry;
  struct SONS_N_VAR *N_var;
  struct SONS_N_VARLET *N_varlet;
};
#endif /* _SAC_SONS_H_ */
