
/**
 * @file traverse_tables.c
 *
 * This file defines the function tables for traversal.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: traverse_tables.c.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#include "traverse_tables.h"
#include "traverse_helper.h"
#include "print.h"
#include "copy_node.h"
#include "free_node.h"
#include "check.h"
#include "rename_identifiers.h"
#include "sum_ints.h"
#include "opt_sub.h"
#include "count_binops.h"
#include "count_identifiers.h"


travtables_t travtables = {
  /* TR_undefined */
  {&TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror}

  /* TR_prt */
  , {&TRAVerror, &PRTprogram, &PRTdeclarations, &PRTmodule, &PRTfundec,
     &PRTextern, &PRTsemicolon, &PRTfundef, &PRTfunbodyblock,
     &PRTl_curly_bracket, &PRTr_curly_bracket, &PRTl_bracket, &PRTr_bracket,
     &PRTcomma, &PRTfunheader, &PRTparams, &PRTparam, &PRTid, &PRTglobaldec,
     &PRTglobaldef, &PRTstmts, &PRTassign, &PRTbinop, &PRTmonop, &PRTvarlet,
     &PRTvar, &PRTnum, &PRTfloat, &PRTbool, &PRTsymboltableentry, &PRTerror}

  /* TR_copy */
  , {&TRAVerror, &COPYprogram, &COPYdeclarations, &COPYmodule, &COPYfundec,
     &COPYextern, &COPYsemicolon, &COPYfundef, &COPYfunbodyblock,
     &COPYl_curly_bracket, &COPYr_curly_bracket, &COPYl_bracket,
     &COPYr_bracket, &COPYcomma, &COPYfunheader, &COPYparams, &COPYparam,
     &COPYid, &COPYglobaldec, &COPYglobaldef, &COPYstmts, &COPYassign,
     &COPYbinop, &COPYmonop, &COPYvarlet, &COPYvar, &COPYnum, &COPYfloat,
     &COPYbool, &COPYsymboltableentry, &COPYerror}

  /* TR_free */
  , {&TRAVerror, &FREEprogram, &FREEdeclarations, &FREEmodule, &FREEfundec,
     &FREEextern, &FREEsemicolon, &FREEfundef, &FREEfunbodyblock,
     &FREEl_curly_bracket, &FREEr_curly_bracket, &FREEl_bracket,
     &FREEr_bracket, &FREEcomma, &FREEfunheader, &FREEparams, &FREEparam,
     &FREEid, &FREEglobaldec, &FREEglobaldef, &FREEstmts, &FREEassign,
     &FREEbinop, &FREEmonop, &FREEvarlet, &FREEvar, &FREEnum, &FREEfloat,
     &FREEbool, &FREEsymboltableentry, &FREEerror}

  /* TR_chk */
  , {&TRAVerror, &CHKprogram, &CHKdeclarations, &CHKmodule, &CHKfundec,
     &CHKextern, &CHKsemicolon, &CHKfundef, &CHKfunbodyblock,
     &CHKl_curly_bracket, &CHKr_curly_bracket, &CHKl_bracket, &CHKr_bracket,
     &CHKcomma, &CHKfunheader, &CHKparams, &CHKparam, &CHKid, &CHKglobaldec,
     &CHKglobaldef, &CHKstmts, &CHKassign, &CHKbinop, &CHKmonop, &CHKvarlet,
     &CHKvar, &CHKnum, &CHKfloat, &CHKbool, &CHKsymboltableentry, &CHKerror}

  /* TR_ri */
  , {&TRAVerror, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &RIvarlet, &RIvar, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons}

  /* TR_si */
  , {&TRAVerror, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons}

  /* TR_os */
  , {&TRAVerror, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &OSbinop, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons}

  /* TR_cbo */
  , {&TRAVerror, &TRAVsons, &TRAVsons, &CBOmodule, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &CBObinop, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons}

  /* TR_ci */
  , {&TRAVerror, &TRAVsons, &TRAVsons, &CImodule, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &CIvarlet, &CIvar, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons}
};

preposttable_t pretable = {
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
};

preposttable_t posttable = {
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
};

const char *travnames[10] = {
  "unknown", "prt", "copy", "free", "chk", "ri", "si", "os", "cbo", "ci"
};
