
/**
 * @file traverse_helper.c
 *
 * Defines the helper function needed by the traversal system
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: traverse_helper.c.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */


#include "traverse_helper.h"
#include "dbug.h"
#include "tree_basic.h"
#include "traverse.h"

#define TRAV( son, info)    if (son != NULL) { son = TRAVdo( son, info); }

node *
TRAVnone (node * arg_node, info * arg_info)
{
  return (arg_node);
}

node *
TRAVerror (node * arg_node, info * arg_info)
{
  DBUG_ASSERT ((FALSE), "Illegal node type found.");

  return (arg_node);
}

node *
TRAVsons (node * arg_node, info * arg_info)
{
  switch (NODE_TYPE (arg_node))
    {
    case N_program:
      TRAV (PROGRAM_DECLARATIONS (arg_node), arg_info);
      break;
    case N_declarations:
      TRAV (DECLARATIONS_DECLARATION (arg_node), arg_info);
      TRAV (DECLARATIONS_DECLARATIONS (arg_node), arg_info);
      break;
    case N_module:
      TRAV (MODULE_STMTS (arg_node), arg_info);
      break;
    case N_fundec:
      TRAV (FUNDEC_KEYWORD (arg_node), arg_info);
      TRAV (FUNDEC_FUNHEADER (arg_node), arg_info);
      TRAV (FUNDEC_SEMICOLON (arg_node), arg_info);
      break;
    case N_extern:
      break;
    case N_semicolon:
      break;
    case N_fundef:
      TRAV (FUNDEF_KEYWORD (arg_node), arg_info);
      TRAV (FUNDEF_FUNHEADER (arg_node), arg_info);
      TRAV (FUNDEF_FUNBODYBLOCK (arg_node), arg_info);
      break;
    case N_funbodyblock:
      TRAV (FUNBODYBLOCK_L_CURLY_BRACKET (arg_node), arg_info);
      TRAV (FUNBODYBLOCK_FUNBODY (arg_node), arg_info);
      TRAV (FUNBODYBLOCK_R_CURLY_BRACKET (arg_node), arg_info);
      break;
    case N_l_curly_bracket:
      break;
    case N_r_curly_bracket:
      break;
    case N_l_bracket:
      break;
    case N_r_bracket:
      break;
    case N_comma:
      break;
    case N_funheader:
      TRAV (FUNHEADER_RETTYPE (arg_node), arg_info);
      TRAV (FUNHEADER_ID (arg_node), arg_info);
      TRAV (FUNHEADER_L_BRACKET (arg_node), arg_info);
      TRAV (FUNHEADER_PARAMS (arg_node), arg_info);
      TRAV (FUNHEADER_R_BRACKET (arg_node), arg_info);
      break;
    case N_params:
      TRAV (PARAMS_PARAM (arg_node), arg_info);
      TRAV (PARAMS_COMMA (arg_node), arg_info);
      TRAV (PARAMS_PARAMS (arg_node), arg_info);
      break;
    case N_param:
      TRAV (PARAM_RETTYPE (arg_node), arg_info);
      TRAV (PARAM_ID (arg_node), arg_info);
      break;
    case N_id:
      break;
    case N_globaldec:
      TRAV (GLOBALDEC_EXTERN (arg_node), arg_info);
      TRAV (GLOBALDEC_TYPE (arg_node), arg_info);
      TRAV (GLOBALDEC_ID (arg_node), arg_info);
      TRAV (GLOBALDEC_SEMICOLON (arg_node), arg_info);
      break;
    case N_globaldef:
      TRAV (GLOBALDEF_EXPORT (arg_node), arg_info);
      TRAV (GLOBALDEF_TYPE (arg_node), arg_info);
      TRAV (GLOBALDEF_ID (arg_node), arg_info);
      TRAV (GLOBALDEF_EXPR (arg_node), arg_info);
      TRAV (GLOBALDEF_SEMICOLON (arg_node), arg_info);
      break;
    case N_stmts:
      TRAV (STMTS_STMT (arg_node), arg_info);
      TRAV (STMTS_NEXT (arg_node), arg_info);
      break;
    case N_assign:
      TRAV (ASSIGN_LET (arg_node), arg_info);
      TRAV (ASSIGN_EXPR (arg_node), arg_info);
      break;
    case N_binop:
      TRAV (BINOP_LEFT (arg_node), arg_info);
      TRAV (BINOP_RIGHT (arg_node), arg_info);
      break;
    case N_monop:
      TRAV (MONOP_RIGHT (arg_node), arg_info);
      break;
    case N_varlet:
      break;
    case N_var:
      break;
    case N_num:
      break;
    case N_float:
      break;
    case N_bool:
      break;
    case N_symboltableentry:
      break;
    case N_error:
      TRAV (ERROR_NEXT (arg_node), arg_info);
      break;
    default:
      DBUG_ASSERT ((FALSE), "Illegal nodetype found!");
      break;
    }

  return (arg_node);
}

int
TRAVnumSons (node * node)
{
  int result = 0;

  DBUG_ENTER ("TRAVnumSons");

  switch (NODE_TYPE (node))
    {
    case N_program:
      result = 1;
      break;
    case N_declarations:
      result = 2;
      break;
    case N_module:
      result = 1;
      break;
    case N_fundec:
      result = 3;
      break;
    case N_extern:
      result = 0;
      break;
    case N_semicolon:
      result = 0;
      break;
    case N_fundef:
      result = 3;
      break;
    case N_funbodyblock:
      result = 3;
      break;
    case N_l_curly_bracket:
      result = 0;
      break;
    case N_r_curly_bracket:
      result = 0;
      break;
    case N_l_bracket:
      result = 0;
      break;
    case N_r_bracket:
      result = 0;
      break;
    case N_comma:
      result = 0;
      break;
    case N_funheader:
      result = 5;
      break;
    case N_params:
      result = 3;
      break;
    case N_param:
      result = 2;
      break;
    case N_id:
      result = 0;
      break;
    case N_globaldec:
      result = 4;
      break;
    case N_globaldef:
      result = 5;
      break;
    case N_stmts:
      result = 2;
      break;
    case N_assign:
      result = 2;
      break;
    case N_binop:
      result = 2;
      break;
    case N_monop:
      result = 1;
      break;
    case N_varlet:
      result = 0;
      break;
    case N_var:
      result = 0;
      break;
    case N_num:
      result = 0;
      break;
    case N_float:
      result = 0;
      break;
    case N_bool:
      result = 0;
      break;
    case N_symboltableentry:
      result = 0;
      break;
    case N_error:
      result = 1;
      break;
    default:
      DBUG_ASSERT ((FALSE), "Illegal nodetype found!");
      break;
    }

  DBUG_RETURN (result);
}

node *
TRAVgetSon (int no, node * parent)
{
  node *result = NULL;

  DBUG_ENTER ("TRAVgetSon");

  switch (NODE_TYPE (parent))
    {
    case N_program:
      switch (no)
	{
	case 0:
	  result = PROGRAM_DECLARATIONS (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_declarations:
      switch (no)
	{
	case 0:
	  result = DECLARATIONS_DECLARATION (parent);
	  break;
	case 1:
	  result = DECLARATIONS_DECLARATIONS (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_module:
      switch (no)
	{
	case 0:
	  result = MODULE_STMTS (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_fundec:
      switch (no)
	{
	case 0:
	  result = FUNDEC_KEYWORD (parent);
	  break;
	case 1:
	  result = FUNDEC_FUNHEADER (parent);
	  break;
	case 2:
	  result = FUNDEC_SEMICOLON (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_extern:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_semicolon:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_fundef:
      switch (no)
	{
	case 0:
	  result = FUNDEF_KEYWORD (parent);
	  break;
	case 1:
	  result = FUNDEF_FUNHEADER (parent);
	  break;
	case 2:
	  result = FUNDEF_FUNBODYBLOCK (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_funbodyblock:
      switch (no)
	{
	case 0:
	  result = FUNBODYBLOCK_L_CURLY_BRACKET (parent);
	  break;
	case 1:
	  result = FUNBODYBLOCK_FUNBODY (parent);
	  break;
	case 2:
	  result = FUNBODYBLOCK_R_CURLY_BRACKET (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_l_curly_bracket:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_r_curly_bracket:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_l_bracket:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_r_bracket:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_comma:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_funheader:
      switch (no)
	{
	case 0:
	  result = FUNHEADER_RETTYPE (parent);
	  break;
	case 1:
	  result = FUNHEADER_ID (parent);
	  break;
	case 2:
	  result = FUNHEADER_L_BRACKET (parent);
	  break;
	case 3:
	  result = FUNHEADER_PARAMS (parent);
	  break;
	case 4:
	  result = FUNHEADER_R_BRACKET (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_params:
      switch (no)
	{
	case 0:
	  result = PARAMS_PARAM (parent);
	  break;
	case 1:
	  result = PARAMS_COMMA (parent);
	  break;
	case 2:
	  result = PARAMS_PARAMS (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_param:
      switch (no)
	{
	case 0:
	  result = PARAM_RETTYPE (parent);
	  break;
	case 1:
	  result = PARAM_ID (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_id:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_globaldec:
      switch (no)
	{
	case 0:
	  result = GLOBALDEC_EXTERN (parent);
	  break;
	case 1:
	  result = GLOBALDEC_TYPE (parent);
	  break;
	case 2:
	  result = GLOBALDEC_ID (parent);
	  break;
	case 3:
	  result = GLOBALDEC_SEMICOLON (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_globaldef:
      switch (no)
	{
	case 0:
	  result = GLOBALDEF_EXPORT (parent);
	  break;
	case 1:
	  result = GLOBALDEF_TYPE (parent);
	  break;
	case 2:
	  result = GLOBALDEF_ID (parent);
	  break;
	case 3:
	  result = GLOBALDEF_EXPR (parent);
	  break;
	case 4:
	  result = GLOBALDEF_SEMICOLON (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_stmts:
      switch (no)
	{
	case 0:
	  result = STMTS_STMT (parent);
	  break;
	case 1:
	  result = STMTS_NEXT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_assign:
      switch (no)
	{
	case 0:
	  result = ASSIGN_LET (parent);
	  break;
	case 1:
	  result = ASSIGN_EXPR (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_binop:
      switch (no)
	{
	case 0:
	  result = BINOP_LEFT (parent);
	  break;
	case 1:
	  result = BINOP_RIGHT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_monop:
      switch (no)
	{
	case 0:
	  result = MONOP_RIGHT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_varlet:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_var:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_num:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_float:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_bool:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_symboltableentry:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_error:
      switch (no)
	{
	case 0:
	  result = ERROR_NEXT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    default:
      DBUG_ASSERT ((FALSE), "Illegal nodetype found!");
      break;
    }

  DBUG_RETURN (result);
}
