
/**
 * @file types_nodetype.h
 *
 * This file defines the nodetype node enumeration.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: types_nodetype.h.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#ifndef _SAC_TYPES_NODETYPE_H_
#define _SAC_TYPES_NODETYPE_H_

#define MAX_NODES 30
typedef enum
{ N_undefined = 0, N_program = 1, N_declarations = 2, N_module = 3, N_fundec =
    4, N_extern = 5, N_semicolon = 6, N_fundef = 7, N_funbodyblock =
    8, N_l_curly_bracket = 9, N_r_curly_bracket = 10, N_l_bracket =
    11, N_r_bracket = 12, N_comma = 13, N_funheader = 14, N_params =
    15, N_param = 16, N_id = 17, N_globaldec = 18, N_globaldef = 19, N_stmts =
    20, N_assign = 21, N_binop = 22, N_monop = 23, N_varlet = 24, N_var =
    25, N_num = 26, N_float = 27, N_bool = 28, N_symboltableentry =
    29, N_error = 30 } nodetype;

#endif /* _SAC_TYPES_NODETYPE_H_ */
